[package]
name = "study-solana-with-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "20.0.2"
num = "0.4.0"
twox-hash = "=1.6.3"
futures = "0.3"
thread_local = "1.1"
